'From Cuis 4.2 of 25 July 2013 [latest update: #2820] on 13 June 2016 at 8:17:25.283191 pm'!


!SmalltalkEditor class methodsFor: 'explain' stamp: 'dhn 6/13/2016 17:37'!
plateA
	"As in boiler plate. Answer a string which appears in several explanations"
	
	^ '.  To see the other definitions,', self plateX! !

!SmalltalkEditor class methodsFor: 'explain' stamp: 'dhn 6/13/2016 17:36'!
plateB
	"As in boiler plate. Answer a string which appears in several explanations"
	
	^ '.  To see the definitions,', self plateX! !

!SmalltalkEditor class methodsFor: 'explain' stamp: 'dhn 6/13/2016 17:35'!
plateX
	"As in boiler plate. Answer a string which appears in several explanations"
	
	^ ' go to the message list pane, get the menu, and select ''implementors of...''."'! !
