'From Cuis 4.1 of 12 December 2012 [latest update: #1581] on 28 January 2013 at 12:16:48 pm'!

!SystemVersion methodsFor: 'testing' stamp: 'jmv 1/28/2013 12:16'!
isCuis
	"Sure we are!!!!
	Warning: It is always better to write code that doesnt depend on platform particularities. Try to avoid calling this method!!"
	^true! !

!SystemVersion methodsFor: 'testing' stamp: 'jmv 1/28/2013 12:16'!
isPharo
	"Nope. We are Cuis.
	Warning: It is always better to write code that doesnt depend on platform particularities. Try to avoid calling this method!!"
	^false! !

!SystemVersion methodsFor: 'testing' stamp: 'jmv 1/28/2013 12:16'!
isSqueak
	"Nope. We are Cuis.
	Warning: It is always better to write code that doesnt depend on platform particularities. Try to avoid calling this method!!"
	^false! !

