'From Cuis 4.2 of 25 July 2013 [latest update: #1832] on 22 September 2013 at 11:31:10.31 pm'!
!methodRemoval: LargeNegativeInteger #ln!
LargeNegativeInteger removeSelector: #ln!
!methodRemoval: LargeNegativeInteger #log!
LargeNegativeInteger removeSelector: #log!
!methodRemoval: LargePositiveInteger #ln!
LargePositiveInteger removeSelector: #ln!
!methodRemoval: LargePositiveInteger #log!
LargePositiveInteger removeSelector: #log!
