'From Cuis 4.2 of 25 July 2013 [latest update: #2155] on 12 January 2015 at 11:12:06.204073 pm'!
!classMoveToSomePackage: #DateAndTimeTest!
Smalltalk removeClassNamedIfInBaseSystem: #DateAndTimeTest!
!classMoveToSomePackage: #TimeTest!
Smalltalk removeClassNamedIfInBaseSystem: #TimeTest!
!classMoveToSomePackage: #MatrixTransform2x3Test!
Smalltalk removeClassNamedIfInBaseSystem: #MatrixTransform2x3Test!
!classMoveToSomePackage: #MorphicLocationTest!
Smalltalk removeClassNamedIfInBaseSystem: #MorphicLocationTest!
!classMoveToSomePackage: #MorphicTranslationTest!
Smalltalk removeClassNamedIfInBaseSystem: #MorphicTranslationTest!
