'From Cuis 4.2 of 25 July 2013 [latest update: #2669] on 24 January 2016 at 11:11:43.355755 pm'!
!classRemoval: #ProtocolCatcher!
Smalltalk removeClassNamed: #ProtocolCatcher!
!classRemoval: #ProtocolCatcher2!
Smalltalk removeClassNamed: #ProtocolCatcher2!
!classRemoval: #StandardFileMenu!
Smalltalk removeClassNamed: #StandardFileMenu!
!classRemoval: #StandardFileMenuResult!
Smalltalk removeClassNamed: #StandardFileMenuResult!
!classRemoval: #Stopwatch!
Smalltalk removeClassNamed: #Stopwatch!
