'From Cuis 5.0 of 7 November 2016 [latest update: #3286] on 4 April 2018 at 4:53:28 pm'!
!classDefinition: #MorphicCanvas category: #'Morphic-Support'!
Object subclass: #MorphicCanvas
	instanceVariableNames: 'form clipLeft clipTop clipRight clipBottom shadowColor transformations currentTransformation cti currentMorph '
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Morphic-Support'!
!classDefinition: #MorphicCanvas category: #'Morphic-Support'!
Object subclass: #MorphicCanvas
	instanceVariableNames: 'form clipLeft clipTop clipRight clipBottom transformations currentTransformation cti currentMorph'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Morphic-Support'!
