'From Cuis 5.0 of 7 November 2016 [latest update: #3437] on 10 September 2018 at 9:10:09 am'!
!methodRemoval: ImageReadWriter #space!
ImageReadWriter removeSelector: #space!
!methodRemoval: ImageReadWriter #tab!
ImageReadWriter removeSelector: #tab!
!methodRemoval: Stream #nextNumber!
Stream removeSelector: #nextNumber!
!methodRemoval: Stream #nextNumber:!
Stream removeSelector: #nextNumber:!
!methodRemoval: Stream #nextNumber:put:!
Stream removeSelector: #nextNumber:put:!
