'From Cuis 5.0 [latest update: #4876] on 22 September 2021 at 4:08:55 pm'!

!Theme methodsFor: 'colors' stamp: 'jmv 9/22/2021 16:08:06'!
background

	"^ `Color r: 0.7 g: 0.72 b: 0.83`."
	^ `Color r: 0.167 g: 0.344 b: 0.629`! !

"Postscript:
Leave the line above, and replace the rest of this comment by a useful one.
Executable statements should follow this comment, and should
be separated by periods, with no exclamation points (!!).
Be sure to put any further comments in double-quotes, like this one."
self runningWorld color: Theme current background.!

