'From Cuis 6.0 [latest update: #6003] on 9 September 2023 at 5:05:37 pm'!
!methodRemoval: TTFontDescription #xappendGlyphDataTo:glyphsArray:indexes:base:bar:unknown:scaleArrowGlyphs: stamp: 'jmv 9/9/2023 17:05:05'!
TTFontDescription removeSelector: #xappendGlyphDataTo:glyphsArray:indexes:base:bar:unknown:scaleArrowGlyphs:!
!methodRemoval: TTFontDescription #xglyphsByUtf8Bytes:unknownGlyph:scaleArrowGlyphs: stamp: 'jmv 9/9/2023 17:00:40'!
TTFontDescription removeSelector: #xglyphsByUtf8Bytes:unknownGlyph:scaleArrowGlyphs:!
!methodRemoval: TTContourConstruction #xinitialMoveToAndPathCommands: stamp: 'jmv 9/9/2023 17:00:43'!
TTContourConstruction removeSelector: #xinitialMoveToAndPathCommands:!
!methodRemoval: TTContourConstruction #xstartPointDo:quadraticBeziersDo: stamp: 'jmv 9/9/2023 17:00:45'!
TTContourConstruction removeSelector: #xstartPointDo:quadraticBeziersDo:!
!methodRemoval: FormGlyph #xdeltaXToCenter stamp: 'jmv 9/9/2023 17:00:48'!
FormGlyph removeSelector: #xdeltaXToCenter!
!methodRemoval: FormGlyph #xdeltaXToCenter: stamp: 'jmv 9/9/2023 17:00:49'!
FormGlyph removeSelector: #xdeltaXToCenter:!
!methodRemoval: Theme class #xloadAdditionalThemes stamp: 'jmv 9/9/2023 17:00:51'!
Theme class removeSelector: #xloadAdditionalThemes!
!methodRemoval: HybridCanvas #xcurrentMorph:drawingMorphStack:currentTransformation:transformations:cti: stamp: 'jmv 9/9/2023 17:00:53'!
HybridCanvas removeSelector: #xcurrentMorph:drawingMorphStack:currentTransformation:transformations:cti:!
!methodRemoval: VectorCanvas #xattachedCanvas: stamp: 'jmv 9/9/2023 17:00:54'!
VectorCanvas removeSelector: #xattachedCanvas:!
!methodRemoval: Sample10PythagorasTree #xdrawTreeOn:p1:p2:depth: stamp: 'jmv 9/9/2023 17:04:50'!
Sample10PythagorasTree removeSelector: #xdrawTreeOn:p1:p2:depth:!
!methodRemoval: Sample10PythagorasTree #xwithMultipleColors stamp: 'jmv 9/9/2023 17:00:56'!
Sample10PythagorasTree removeSelector: #xwithMultipleColors!
!methodRemoval: Clipboard #xretrieveIdOrStringFromOS stamp: 'jmv 9/9/2023 17:00:58'!
Clipboard removeSelector: #xretrieveIdOrStringFromOS!
!methodRemoval: CodePackage #xmessageSendsCount stamp: 'jmv 9/9/2023 17:03:49'!
CodePackage removeSelector: #xmessageSendsCount!
!methodRemoval: Scanner class #xtypeTable:at: stamp: 'jmv 9/9/2023 17:01:00'!
Scanner class removeSelector: #xtypeTable:at:!
!methodRemoval: DataStream #xreadUnicodeString stamp: 'jmv 9/9/2023 17:01:09'!
DataStream removeSelector: #xreadUnicodeString!
!methodRemoval: DataStream #xwriteUnicodeString: stamp: 'jmv 9/9/2023 17:01:04'!
DataStream removeSelector: #xwriteUnicodeString:!
!methodRemoval: DataStream #xwriteUnicodeSymbol: stamp: 'jmv 9/9/2023 17:01:02'!
DataStream removeSelector: #xwriteUnicodeSymbol:!
!methodRemoval: DataStream #xreadUnicodeSymbol stamp: 'jmv 9/9/2023 17:01:07'!
DataStream removeSelector: #xreadUnicodeSymbol!
!methodRemoval: UniFileStream #xuseUnicodeString stamp: 'jmv 9/9/2023 17:02:10'!
UniFileStream removeSelector: #xuseUnicodeString!
!methodRemoval: Stream #xnextUnicodeStringPut: stamp: 'jmv 9/9/2023 17:02:12'!
Stream removeSelector: #xnextUnicodeStringPut:!
!methodRemoval: Stream #xnextUnicodeString stamp: 'jmv 9/9/2023 17:02:14'!
Stream removeSelector: #xnextUnicodeString!
!methodRemoval: SystemDictionary #xlastCommandLineArguments stamp: 'jmv 9/9/2023 17:02:17'!
SystemDictionary removeSelector: #xlastCommandLineArguments!
!methodRemoval: SystemDictionary #xprocessCommandLineOption:optionArgument:raiseExceptions: stamp: 'jmv 9/9/2023 17:02:19'!
SystemDictionary removeSelector: #xprocessCommandLineOption:optionArgument:raiseExceptions:!
!methodRemoval: SystemDictionary #xdisplaySystemInformationStringOn: stamp: 'jmv 9/9/2023 17:02:22'!
SystemDictionary removeSelector: #xdisplaySystemInformationStringOn:!
!methodRemoval: SystemDictionary #xdisplayCommandLineUsageOn: stamp: 'jmv 9/9/2023 17:02:25'!
SystemDictionary removeSelector: #xdisplayCommandLineUsageOn:!
!methodRemoval: Text #xasUnicodeStringOrText stamp: 'jmv 9/9/2023 17:02:27'!
Text removeSelector: #xasUnicodeStringOrText!
!methodRemoval: CompiledMethod #xmessageSendsCount stamp: 'jmv 9/9/2023 17:03:54'!
CompiledMethod removeSelector: #xmessageSendsCount!
!methodRemoval: UnicodeString class #xutf8FromCodePoints: stamp: 'jmv 9/9/2023 17:02:30'!
UnicodeString class removeSelector: #xutf8FromCodePoints:!
!methodRemoval: UnicodeString class #xcodePointsFromUtf8: stamp: 'jmv 9/9/2023 17:02:32'!
UnicodeString class removeSelector: #xcodePointsFromUtf8:!
!methodRemoval: UnicodeString #xbasicCanonicalDecomposition stamp: 'jmv 9/9/2023 17:02:59'!
UnicodeString removeSelector: #xbasicCanonicalDecomposition!
!methodRemoval: UnicodeString #xcanonicalComposition stamp: 'jmv 9/9/2023 17:02:06'!
UnicodeString removeSelector: #xcanonicalComposition!
!methodRemoval: UnicodeString #xbasicCompose:on: stamp: 'jmv 9/9/2023 17:03:12'!
UnicodeString removeSelector: #xbasicCompose:on:!
!methodRemoval: UnicodeString #xfindCanonicalCompositionAndHash stamp: 'jmv 9/9/2023 17:02:52'!
UnicodeString removeSelector: #xfindCanonicalCompositionAndHash!
!methodRemoval: UnicodeString #xbasicCanonicallyOrdered stamp: 'jmv 9/9/2023 17:03:04'!
UnicodeString removeSelector: #xbasicCanonicallyOrdered!
!methodRemoval: UnicodeString #xisInCanonicalCompositionForm stamp: 'jmv 9/9/2023 17:01:58'!
UnicodeString removeSelector: #xisInCanonicalCompositionForm!
!methodRemoval: UnicodeString #xcanonicalDecomposition stamp: 'jmv 9/9/2023 17:02:48'!
UnicodeString removeSelector: #xcanonicalDecomposition!
!methodRemoval: UnicodeString #xasUnicodeString stamp: 'jmv 9/9/2023 17:02:41'!
UnicodeString removeSelector: #xasUnicodeString!
!methodRemoval: UnicodeString #xbasicCanonicalComposition stamp: 'jmv 9/9/2023 17:02:55'!
UnicodeString removeSelector: #xbasicCanonicalComposition!
!methodRemoval: UnicodeString #xisUnicodeString stamp: 'jmv 9/9/2023 17:02:43'!
UnicodeString removeSelector: #xisUnicodeString!
!methodRemoval: String class #xfromUtf8Bytes:trimLastNull: stamp: 'jmv 9/9/2023 17:01:55'!
String class removeSelector: #xfromUtf8Bytes:trimLastNull:!
!methodRemoval: String #xisInCanonicalCompositionForm stamp: 'jmv 9/9/2023 17:01:52'!
String removeSelector: #xisInCanonicalCompositionForm!
!methodRemoval: CharacterSequence #xasUnicodeString stamp: 'jmv 9/9/2023 17:02:38'!
CharacterSequence removeSelector: #xasUnicodeString!
!methodRemoval: CharacterSequence #xcanonicalComposition stamp: 'jmv 9/9/2023 17:01:44'!
CharacterSequence removeSelector: #xcanonicalComposition!
!methodRemoval: CharacterSequence #xasUnicodeStringOrText stamp: 'jmv 9/9/2023 17:01:41'!
CharacterSequence removeSelector: #xasUnicodeStringOrText!
!methodRemoval: CharacterSequence #xcanonicalDecomposition stamp: 'jmv 9/9/2023 17:01:48'!
CharacterSequence removeSelector: #xcanonicalDecomposition!
!methodRemoval: SequenceableCollection #xfindFirst:startingAt: stamp: 'jmv 9/9/2023 17:01:37'!
SequenceableCollection removeSelector: #xfindFirst:startingAt:!
!methodRemoval: UnicodeCodePoint class #xcanonicalDecomposition:on: stamp: 'jmv 9/9/2023 17:04:36'!
UnicodeCodePoint class removeSelector: #xcanonicalDecomposition:on:!
!methodRemoval: UnicodeCodePoint class #xnamedCharactersMap stamp: 'jmv 9/9/2023 17:01:32'!
UnicodeCodePoint class removeSelector: #xnamedCharactersMap!
!methodRemoval: UnicodeCodePoint class #xcombiningClass: stamp: 'jmv 9/9/2023 17:03:06'!
UnicodeCodePoint class removeSelector: #xcombiningClass:!
!methodRemoval: UnicodeCodePoint class #xisDiacriticalMark: stamp: 'jmv 9/9/2023 17:03:09'!
UnicodeCodePoint class removeSelector: #xisDiacriticalMark:!
!methodRemoval: UnicodeCodePoint class #xcanonicalCompositionOf:and: stamp: 'jmv 9/9/2023 17:03:18'!
UnicodeCodePoint class removeSelector: #xcanonicalCompositionOf:and:!
!methodRemoval: UnicodeCodePoint #xisNullCharacter stamp: 'jmv 9/9/2023 17:01:29'!
UnicodeCodePoint removeSelector: #xisNullCharacter!
!methodRemoval: UnicodeCodePoint #xisDiacriticalMark stamp: 'jmv 9/9/2023 17:01:27'!
UnicodeCodePoint removeSelector: #xisDiacriticalMark!
!methodRemoval: UnicodeCodePoint #xisSymbolLike stamp: 'jmv 9/9/2023 17:04:21'!
UnicodeCodePoint removeSelector: #xisSymbolLike!
!methodRemoval: Character #xisNullCharacter stamp: 'jmv 9/9/2023 17:01:24'!
Character removeSelector: #xisNullCharacter!
!methodRemoval: Character #xisDiacriticalMark stamp: 'jmv 9/9/2023 17:01:22'!
Character removeSelector: #xisDiacriticalMark!
!methodRemoval: Character #xisSymbolLike stamp: 'jmv 9/9/2023 17:04:16'!
Character removeSelector: #xisSymbolLike!
!methodRemoval: SystemOrganizer #xmessageSendsCountOf: stamp: 'jmv 9/9/2023 17:01:20'!
SystemOrganizer removeSelector: #xmessageSendsCountOf:!
!methodRemoval: ClassDescription #xselectorsInCategory: stamp: 'jmv 9/9/2023 17:01:18'!
ClassDescription removeSelector: #xselectorsInCategory:!
!methodRemoval: ClassDescription #xmessagesCountInCategory: stamp: 'jmv 9/9/2023 17:01:16'!
ClassDescription removeSelector: #xmessagesCountInCategory:!
!methodRemoval: ClassDescription #xmessageSendsCountInCategory: stamp: 'jmv 9/9/2023 17:01:14'!
ClassDescription removeSelector: #xmessageSendsCountInCategory:!
!methodRemoval: ClassDescription #xmessageSendsCount stamp: 'jmv 9/9/2023 17:03:48'!
ClassDescription removeSelector: #xmessageSendsCount!
!methodRemoval: CodeProvider #xannotationForMessageCategory:ofClass: stamp: 'jmv 9/9/2023 17:01:12'!
CodeProvider removeSelector: #xannotationForMessageCategory:ofClass:!
!methodRemoval: TextModel #xisDirty stamp: 'jmv 9/9/2023 17:01:11'!
TextModel removeSelector: #xisDirty!
!methodRemoval: Object #xisUnicodeString stamp: 'jmv 9/9/2023 17:03:15'!
Object removeSelector: #xisUnicodeString!
