'From Cuis 6.0 [latest update: #6039] on 10 October 2023 at 5:33:44 pm'!
!methodRemoval: HybridCanvas #resetCanvas stamp: 'jmv 10/10/2023 17:32:40'!
HybridCanvas removeSelector: #resetCanvas!
!methodRemoval: BitBltCanvas #resetCanvas stamp: 'jmv 10/10/2023 17:32:41'!
BitBltCanvas removeSelector: #resetCanvas!
!methodRemoval: VectorCanvas #resetCanvas stamp: 'jmv 10/10/2023 17:32:42'!
VectorCanvas removeSelector: #resetCanvas!
!methodRemoval: MorphicCanvas #resetCanvas stamp: 'jmv 10/10/2023 17:32:43'!
MorphicCanvas removeSelector: #resetCanvas!
!methodRemoval: MorphicCanvas #ensureCurrentMorphIsWorld stamp: 'jmv 10/10/2023 17:32:30'!
MorphicCanvas removeSelector: #ensureCurrentMorphIsWorld!
!methodRemoval: WorldMorph #doOneCycleNow stamp: 'jmv 10/10/2023 17:32:24'!
WorldMorph removeSelector: #doOneCycleNow!
!methodRemoval: WorldMorph #clearCanvas stamp: 'jmv 10/10/2023 17:32:59'!
WorldMorph removeSelector: #clearCanvas!
!methodRemoval: WorldMorph #resetCanvas stamp: 'jmv 10/10/2023 17:32:45'!
WorldMorph removeSelector: #resetCanvas!
!methodRemoval: WorldMorph #displayWorld stamp: 'jmv 10/10/2023 17:32:57'!
WorldMorph removeSelector: #displayWorld!
!methodRemoval: WorldMorph #doOneCycle: stamp: 'jmv 10/10/2023 17:32:20'!
WorldMorph removeSelector: #doOneCycle:!
!methodRemoval: WorldMorph #canvas stamp: 'jmv 10/10/2023 17:33:24'!
WorldMorph removeSelector: #canvas!
!methodRemoval: Morph #boundsFinderCanvas stamp: 'jmv 10/10/2023 17:33:16'!
Morph removeSelector: #boundsFinderCanvas!
!methodRemoval: Morph #canvas stamp: 'jmv 10/10/2023 17:33:20'!
Morph removeSelector: #canvas!
