'From Cuis7.1 [latest update: #6452] on 6 June 2024 at 5:26:22 pm'!

!Character class methodsFor: 'accessing untypeable characters' stamp: 'jmv 6/6/2024 14:32:09'!
backQuote
	"Not specifically untypeable, but cumbersome to use in source code."

	^ `Character codePoint: 96`! !

!Character class methodsFor: 'accessing untypeable characters' stamp: 'jmv 6/6/2024 14:31:09'!
doubleQuote
	"Not specifically untypeable, but cumbersome to use in source code."

	^ `Character codePoint: 34`! !

!Character class methodsFor: 'accessing untypeable characters' stamp: 'jmv 6/6/2024 17:26:00'!
noBreakSpace

	^ `Character codePoint: 16rA0`! !

!Character class methodsFor: 'accessing untypeable characters' stamp: 'jmv 6/6/2024 14:31:33'!
singleQuote
	"Not specifically untypeable, but cumbersome to use in source code."

	^ `Character codePoint: 39`! !

