'From Cuis7.1 [latest update: #6594] on 16 August 2024 at 9:55:00 am'!
!methodRemoval: SystemDictionary #processCommandLineArguments stamp: 'jmv 8/16/2024 09:54:42'!
SystemDictionary removeSelector: #processCommandLineArguments!
!methodRemoval: SystemDictionary #processCommandLineOption:optionArgument:raiseExceptions: stamp: 'jmv 8/16/2024 09:54:42'!
SystemDictionary removeSelector: #processCommandLineOption:optionArgument:raiseExceptions:!
