'From Cuis7.1 [latest update: #6768] on 10 October 2024 at 12:07:29 pm'!
!methodRemoval: FileEntry #isFile stamp: 'jmv 10/10/2024 12:06:57'!
FileEntry removeSelector: #isFile!
!methodRemoval: DirectoryEntry #isDirectory stamp: 'jmv 10/10/2024 12:07:01'!
DirectoryEntry removeSelector: #isDirectory!
!methodRemoval: DirectoryEntry #isFile stamp: 'jmv 10/10/2024 12:06:58'!
DirectoryEntry removeSelector: #isFile!
!methodRemoval: FileSystemEntry #isDirectory stamp: 'jmv 10/10/2024 12:07:02'!
FileSystemEntry removeSelector: #isDirectory!
!methodRemoval: FileSystemEntry #isFile stamp: 'jmv 10/10/2024 12:06:59'!
FileSystemEntry removeSelector: #isFile!
!methodRemoval: UniFileStream #isDirectory stamp: 'jmv 10/10/2024 12:07:03'!
UniFileStream removeSelector: #isDirectory!
