'From Cuis7.5 [latest update: #7280] on 26 June 2025 at 5:01:47 pm'!
!methodRemoval: DisplayScreen class #screenUpdateRequired: stamp: 'jmv 6/26/2025 17:01:03'!
DisplayScreen class removeSelector: #screenUpdateRequired:!
"Postscript:
Leave the line above, and replace the rest of this comment by a useful one.
Executable statements should follow this comment, and should
be separated by periods, with no exclamation points (!!).
Be sure to put any further comments in double-quotes, like this one."
DisplayScreen terminateScreenUpdater!

