'From Cuis7.5 [latest update: #7372] on 25 July 2025 at 9:47:48 am'!
!classDefinition: #LinearLayoutMorph category: #'Morphic-Layouts'!
LayoutMorph subclass: #LinearLayoutMorph
	instanceVariableNames: 'doAdoptWidgetsColor layout '
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Morphic-Layouts'!
!classDefinition: #LinearLayoutMorph category: #'Morphic-Layouts'!
LayoutMorph subclass: #LinearLayoutMorph
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Morphic-Layouts'!
