'From Cuis7.9 [latest update: #8119] on 31 July 2026 at 11:25:36 am'!

!CompiledMethod methodsFor: 'accessing-pragmas & properties' stamp: 'jmv 31/Jul/2026, 2:11:38 pm (UTC)'!
addPragmaOrProperty: aPragmaOrAssociation
	self properties: (self properties copyWith: aPragmaOrAssociation)! !

!methodRemoval: CompiledMethod #addPragma: stamp: 'jmv 31/Jul/2026, 2:25:02 pm (UTC)'!
CompiledMethod removeSelector: #addPragma:!
